# GET http://localhost:3001/api/notes/

# ###
POST http://localhost:3001/api/notes/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjgsImVtYWlsIjoiam9lMkBnbWFpbC5jb20iLCJpYXQiOjE2ODMwNTY5ODN9.1y1jJ7lEzB26nRrFLIhgPLTYjTkH7O3lgZZDNIHB95Q

{
    "content": "sample",
    "important": true
}